.\" Manpage for lowbat
.\" Contact bousset.rudy@gmail.com to correct errors and typos.
.TH lowbat 1 "15 Nov 2019" "lowbat 1.1" "Lowbat Reference"
.SH NAME
lowbat \- Lightweight battery warning utility
.SH SYNOPSYS
.B lowbat
[\fB\-\-say\fR \fIMESSAGE\fR]
[\fB\-\-silent\fR]
.SH DESCRIPTION
.BR lowbat
is a small script meant to be run in the background.
It warns you using
.BR notify\-send
and
.BR espeak
when your battery is falling under 15%.
.SH OPTIONS
.TP
.BR \-\-say =\fIMESSAGE\fR
Sets a custom message.
.TP
.BR \-\-silent
Disables \fBespeak\fR.
.SH BUGS
No known bugs.
.SH AUTHOR
Joe
.SH SEE ALSO
dunst(1), notify-send(1), espeak(1)
