.\" Manpage for lowbat
.\" Contact bousset.rudy@gmail.com to correct errors and typos.
.TH man 1 "14 Nov 2019" "1.0" "lowbat man page"
.SH NAME
lowbat \- warns when battery is running low
.SH SYNOPSYS
.B
lowbat
.SH DESCRIPTION
Very small script meant to be run in the background. It warns you using
.B
notify-send
and
.B
espeak
when your battery is falling under 15%.
