.\" Manpage for lowbat
.\" Contact bousset.rudy@gmail.com to correct errors and typos.
.TH man 1 "14 Nov 2019" "1.0" "lowbat Reference"
.SH NAME
lowbat \- Lightweight battery warning utility
.SH SYNOPSYS
.B lowbat
[OPTION]
.SH DESCRIPTION
.B lowbat
is a small script meant to be run in the background. It warns you using
.B notify-send
and
.B espeak
when your battery is falling under 15%.
.SH OPTIONS
.B lowbat
does only take one option. You can enter a string as an as an argument. It will come as a replacement for the default warning message.
.SH BUGS
No known bugs.
.SH AUTHOR
Joe
.SH SEE ALSO
dunst(1), notify-send(1), espeak(1)
