* lowbat
Very small program that runs in the background and warns you when your battery is low until you plug your laptop in. It also is POSIX-compliant, which is nice.

** Dependencies
- ~acpi~
- ~libnotify~
- ~espeak~
- ~make~
- ~gcc~

** Installation
Open a terminal and run these commands:

#+BEGIN_SRC shell
git clone https://github.com/JozanLeClerc/lowbat.git
cd lowbat
make
sudo make install
#+END_SRC

Next you must find a way to get the script running right after loging in. Add this to your startup programs manager/rc file of choice:

#+BEGIN_SRC shell
lowbat > /dev/null 2>&1 &
#+END_SRC

/Note:/ to get notifications, make sure ~dunst~ is running in the background. In your startup programs manager/rc:
#+BEGIN_SRC shell
dunst > /dev/null 2>&1 &
#+END_SRC

** Options
Two options are available:
- ~--say [MESSAGE]~ allows you to set your own warning message lowbat is active.
- ~--silent~ disables audio warnings.

**** Examples of use:
#+BEGIN_SRC shell
lowbat --say "your custom message" > /dev/null 2>&1 &
#+END_SRC

#+BEGIN_SRC shell
lowbat --silent > /dev/null 2>&1 &
#+END_SRC

** Uninstallation
#+BEGIN_SRC shell
sudo make uninstall
#+END_SRC

** See also
For more informations, check ~man lowbat~.
